package Formularios;

import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author joanm
 */
public final class Frm_menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menu_principal
     */
    // Acá se instancia el panel de alta usuario
    Panel_Alta_Usuario alta_Usuario = new Panel_Alta_Usuario();

    // Acá se instancia el panel de modificación de usuario
    PnlModificarUsuario modificarUsuario = new PnlModificarUsuario();

    // Acá se instancia el panel de búsqueda de usuario
    PnlBuscarUsuario buscarUsuario = new PnlBuscarUsuario();

    // Acá se instancia el panel de eliminación de usuario
    PnlBorrarUsuario borrarUsuario = new PnlBorrarUsuario();

    CardLayout vista;

    public Frm_menu_principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        iconoFormulario();
        vista = (CardLayout) PnlVistaPrincipal.getLayout();
    }

    // Se instancia y configura el ícono del programa.
    public void iconoFormulario() {
        URL url = getClass().getResource("/imgs/iconoDelSistema.png");
        ImageIcon icono_formulario = new ImageIcon(url);
        setIconImage(icono_formulario.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JToggleButton();
        btn_busqueda = new javax.swing.JToggleButton();
        btn_modificar = new javax.swing.JToggleButton();
        btn_salir = new javax.swing.JButton();
        btn_alta = new javax.swing.JToggleButton();
        PnlVistaPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema ABCM de usuarios");

        jPanel1.setBackground(new java.awt.Color(246, 201, 14));

        jPanel2.setBackground(new java.awt.Color(82, 87, 93));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 244, 230));
        jLabel1.setText("Menú del sistema");

        btn_borrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deleteUser.png"))); // NOI18N
        btn_borrar.setText("Borrar usuario");
        btn_borrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_borrar.setPreferredSize(new java.awt.Dimension(185, 81));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_busqueda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/SearchUser.png"))); // NOI18N
        btn_busqueda.setText("Buscar usuario");
        btn_busqueda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_busqueda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ModifyUser.png"))); // NOI18N
        btn_modificar.setText("Modificar usuario");
        btn_modificar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_modificar.setPreferredSize(new java.awt.Dimension(185, 81));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Exit.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_salir.setIconTextGap(25);
        btn_salir.setPreferredSize(new java.awt.Dimension(185, 81));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_alta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_alta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/newUser.png"))); // NOI18N
        btn_alta.setText("Nuevo usuario");
        btn_alta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_alta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_alta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_busqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btn_alta)
                .addGap(60, 60, 60)
                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PnlVistaPrincipal.setBackground(new java.awt.Color(246, 201, 14));
        PnlVistaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(PnlVistaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PnlVistaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaActionPerformed

        // Se hace un condicional para que el botón quede resaltado en color blanco y el resto de los botones quede en gris.
        // De esta manera "se bloquea" el acceso a los otros botones mediante el método .setEnabled(false)
        if (btn_alta.isSelected()) {
            PnlVistaPrincipal.add(alta_Usuario, "alta");
            vista.show(PnlVistaPrincipal, "alta");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();

            btn_busqueda.setEnabled(false);
            btn_borrar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_alta.setBackground(Color.white);
        } else {

            // Si no está presionado, el .removeAll "limpia" todo el panel que contiene la vista principal.
            // swingUtilites es para que actualice el UI y this.repaint(). Por último, se activan los otros botones de vuelta.
            // Para ponerle el color de vuelta al btn_alta, se declaran los 3 valores que están en el diseño
            PnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_busqueda.setEnabled(true);
            btn_borrar.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_alta.setBackground(new Color(240, 240, 240));
        }
    }//GEN-LAST:event_btn_altaActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        if (btn_modificar.isSelected()) {
            PnlVistaPrincipal.add(modificarUsuario, "modificar");
            vista.show(PnlVistaPrincipal, "modificar");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();

            btn_busqueda.setEnabled(false);
            btn_borrar.setEnabled(false);
            btn_alta.setEnabled(false);
            btn_modificar.setBackground(Color.white);

        } else {
            // Si no está presionado, el .removeAll "limpia" todo el panel que contiene la vista principal.
            // swingUtilites es para que actualice el UI y this.repaint(). Por último, se activan los otros botones de vuelta.
            // Para ponerle el color de vuelta al btn_modificar, se declaran los 3 valores que están en el diseño
            PnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_busqueda.setEnabled(true);
            btn_borrar.setEnabled(true);
            btn_alta.setEnabled(true);
            btn_modificar.setBackground(new Color(240, 240, 240));
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed
        if (btn_busqueda.isSelected()) {

            PnlVistaPrincipal.add(buscarUsuario, "buscar");
            vista.show(PnlVistaPrincipal, "buscar");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();

            btn_modificar.setEnabled(false);
            btn_borrar.setEnabled(false);
            btn_alta.setEnabled(false);
            btn_busqueda.setBackground(Color.white);

        } else {
            // Si no está presionado, el .removeAll "limpia" todo el panel que contiene la vista principal.
            // swingUtilites es para que actualice el UI y this.repaint(). Por último, se activan los otros botones de vuelta.
            // Para ponerle el color de vuelta al btn_búsqueda, se declaran los 3 valores que están en el diseño
            PnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_modificar.setEnabled(true);
            btn_borrar.setEnabled(true);
            btn_alta.setEnabled(true);
            btn_busqueda.setBackground(new Color(240, 240, 240));
        }
    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        
        if (btn_borrar.isSelected()) {
        PnlVistaPrincipal.add(borrarUsuario, "borrar");
        vista.show(PnlVistaPrincipal, "borrar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        
            btn_modificar.setEnabled(false);
            btn_busqueda.setEnabled(false);
            btn_alta.setEnabled(false);
            btn_borrar.setBackground(Color.white);

        } else {
            // Si no está presionado, el .removeAll "limpia" todo el panel que contiene la vista principal.
            // swingUtilites es para que actualice el UI y this.repaint(). Por último, se activan los otros botones de vuelta.
            // Para ponerle el color de vuelta al btn_borrar, se declaran los 3 valores que están en el diseño
            PnlVistaPrincipal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            btn_modificar.setEnabled(true);
            btn_busqueda.setEnabled(true);
            btn_alta.setEnabled(true);
            btn_borrar.setBackground(new Color(240, 240, 240));
        }
    }//GEN-LAST:event_btn_borrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlVistaPrincipal;
    private javax.swing.JToggleButton btn_alta;
    private javax.swing.JToggleButton btn_borrar;
    private javax.swing.JToggleButton btn_busqueda;
    private javax.swing.JToggleButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
